async function HPOP_WASM(moduleArg={}){var moduleRtn;var h=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(ca){const {createRequire:a}=await import("node:module");var require=a(import.meta.url)}var ea="./this.program",q=(a,b)=>{throw b;},fa=import.meta.url,r="",ha,ia;
if(ca){var fs=require("node:fs");fa.startsWith("file:")&&(r=require("node:path").dirname(require("node:url").fileURLToPath(fa))+"/");ia=a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a)};ha=async a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);q=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{r=(new URL(".",fa)).href}catch{}ha=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();
throw Error(a.status+" : "+a.url);}}console.log.bind(console);var t=console.error.bind(console),u,v=!1,ka,ja=a=>a.startsWith("file://"),la,ma,B,C,D,E,F,G,na,oa,pa,qa,ra=!1;function sa(){var a=H.buffer;B=new Int8Array(a);D=new Int16Array(a);C=new Uint8Array(a);E=new Uint16Array(a);F=new Int32Array(a);G=new Uint32Array(a);na=new Float32Array(a);oa=new Float64Array(a);pa=new BigInt64Array(a);qa=new BigUint64Array(a)}
function ta(a){h.onAbort?.(a);a="Aborted("+a+")";t(a);v=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ma?.(a);throw a;}var ua;async function va(a){if(!u)try{var b=await ha(a);return new Uint8Array(b)}catch{}if(a==ua&&u)a=new Uint8Array(u);else if(ia)a=ia(a);else throw"both async and sync fetching of the wasm failed";return a}
async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){t(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}async function ya(a){var b=ua;if(!u&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){t(`wasm streaming compile failed: ${d}`),t("falling back to ArrayBuffer instantiation")}return wa(b,a)}
class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Aa=a=>{for(;0<a.length;)a.shift()(h)},Ba=[],Ca=[],Da=()=>{var a=h.preRun.shift();Ca.push(a)},I=!0,K=[],Ea=0,L=0;class Fa{constructor(a){this.s=a;this.h=a-24}}
var Ha=a=>{var b=L;if(!b)return M(0),0;var c=new Fa(b);G[c.h+16>>2]=b;var d=G[c.h+4>>2];if(!d)return M(0),b;for(var e of a){if(0===e||e===d)break;if(Ga(e,d,c.h+16))return M(e),b}M(d);return b},N=a=>{for(var b="";;){var c=C[a++];if(!c)return b;b+=String.fromCharCode(c)}},O={},P={},Ia={},Q=class extends Error{constructor(a){super(a);this.name="BindingError"}},Ja=a=>{throw new Q(a);};
function Ka(a,b,c={}){var d=b.name;if(!a)throw new Q(`type "${d}" must have a positive integer typeid pointer`);if(P.hasOwnProperty(a)){if(c.u)return;throw new Q(`Cannot register type '${d}' twice`);}P[a]=b;delete Ia[a];O.hasOwnProperty(a)&&(b=O[a],delete O[a],b.forEach(e=>e()))}function R(a,b,c={}){return Ka(a,b,c)}
var La=(a,b,c)=>{switch(b){case 1:return c?d=>B[d]:d=>C[d];case 2:return c?d=>D[d>>1]:d=>E[d>>1];case 4:return c?d=>F[d>>2]:d=>G[d>>2];case 8:return c?d=>pa[d>>3]:d=>qa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ma=[],S=[0,1,,1,null,1,!0,1,!1,1],Na=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Ma.pop()||S.length;S[b]=a;S[b+1]=1;return b}};function Oa(a){return this.g(G[a>>2])}
var Pa={name:"emscripten::val",g:a=>{if(!a)throw new Q(`Cannot use deleted val. handle = ${a}`);var b=S[a];9<a&&0===--S[a+1]&&(S[a]=void 0,Ma.push(a));return b},l:(a,b)=>Na(b),m:Oa,j:null},Qa=(a,b)=>{switch(b){case 4:return function(c){return this.g(na[c>>2])};case 8:return function(c){return this.g(oa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ra=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Sa(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].j)return!0;return!1}
var Ta=(a,b)=>{if(void 0===h[a].i){var c=h[a];h[a]=function(...d){if(!h[a].i.hasOwnProperty(d.length))throw new Q(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${h[a].i})!`);return h[a].i[d.length].apply(this,d)};h[a].i=[];h[a].i[c.o]=c}},Ua=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].i&&void 0!==h[a].i[c])throw new Q(`Cannot register public name '${a}' twice`);Ta(a,a);if(h[a].i.hasOwnProperty(c))throw new Q(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].i[c]=b}else h[a]=b,h[a].o=c},Va=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(G[b+4*d>>2]);return c},Wa=class extends Error{constructor(a){super(a);this.name="InternalError"}},Xa=[],T=a=>{var b=Xa[a];b||(Xa[a]=b=Ya.get(a));return b},Za=(a,b)=>{a=N(a);var c=T(b);if("function"!=typeof c)throw new Q(`unknown function pointer with signature ${a}: ${b}`);return c};class $a extends Error{}
var bb=a=>{a=ab(a);var b=N(a);U(a);return b},cb=(a,b)=>{function c(f){e[f]||P[f]||(Ia[f]?Ia[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new $a(`${a}: `+d.map(bb).join([", "]));},fb=(a,b)=>{function c(k){k=b(k);if(k.length!==d.length)throw new Wa("Mismatched type converter count");for(var m=0;m<d.length;++m)R(d[m],k[m])}var d=[];d.forEach(k=>Ia[k]=a);var e=Array(a.length),f=[],g=0;for(let [k,m]of a.entries())P.hasOwnProperty(m)?e[k]=P[m]:(f.push(m),O.hasOwnProperty(m)||(O[m]=
[]),O[m].push(()=>{e[k]=P[m];++g;g===f.length&&c(e)}));0===f.length&&c(e)},gb=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},V=(a,b,c)=>{var d=C;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=
128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},hb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ib=globalThis.TextDecoder&&new TextDecoder,jb=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},kb=(a=0,b,c)=>{var d=C;b=jb(d,a,b,c);if(16<b-a&&d.buffer&&ib)return ib.decode(d.subarray(a,b));for(c="";a<b;){var e=d[a++];if(e&128){var f=d[a++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=
d[a++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|d[a++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},lb=(a,b,c)=>a?kb(a,b,c):"",mb=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,nb=(a,b,c)=>{a>>=1;b=jb(E,a,b/2,c);if(16<b-a&&mb)return mb.decode(E.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(E[a]);return c},ob=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?
c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d},pb=a=>2*a.length,qb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=G[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},rb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;F[b>>2]=f;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d},sb=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},tb=0,W={},ub=a=>{ka=a;
I||0<tb||(h.onExit?.(a),v=!0);q(a,new za(a))},vb=a=>{if(!v)try{a()}catch(b){b instanceof za||"unwind"==b||q(1,b)}finally{if(!(I||0<tb))try{ka=a=ka,ub(a)}catch(b){b instanceof za||"unwind"==b||q(1,b)}}},wb={},yb=()=>{if(!xb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in wb)void 0===wb[b]?delete a[b]:a[b]=wb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);xb=c}return xb},
xb,Ab=(a,b,c,d)=>{var e={string:l=>{var p=0;if(null!==l&&void 0!==l&&0!==l){p=hb(l)+1;var y=zb(p);V(l,y,p);p=y}return p},array:l=>{var p=zb(l.length);B.set(l,p);return p}};a=h["_"+a];var f=[],g=0;if(d)for(var k=0;k<d.length;k++){var m=e[c[k]];m?(0===g&&(g=X()),f[k]=m(d[k])):f[k]=d[k]}c=a(...f);return c=function(l){0!==g&&Y(g);return"string"===b?l?kb(l):"":"boolean"===b?!!l:l}(c)};h.noExitRuntime&&(I=h.noExitRuntime);h.printErr&&(t=h.printErr);h.wasmBinary&&(u=h.wasmBinary);h.thisProgram&&(ea=h.thisProgram);
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.ccall=Ab;h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>Ab(a,b,c,f,d)};h.UTF8ToString=lb;h.stringToUTF8=(a,b,c)=>V(a,b,c);h.lengthBytesUTF8=hb;
var ab,Bb,Cb,U,Z,M,Y,zb,X,Db,Eb,Ga,Fb,H,Ya,Yb={__cxa_begin_catch:a=>{var b=new Fa(a);0==B[b.h+12]&&(B[b.h+12]=1,Ea--);B[b.h+13]=0;K.push(b);return Fb(a)},__cxa_end_catch:()=>{Z(0,0);var a=K.pop();Db(a.s);L=0},__cxa_find_matching_catch_2:()=>Ha([]),__cxa_find_matching_catch_3:a=>Ha([a]),__cxa_rethrow:()=>{var a=K.pop();a||ta("no exception to throw");var b=a.s;0==B[a.h+13]&&(K.push(a),B[a.h+13]=1,B[a.h+12]=0,Ea++);Eb(b);L=b;throw L;},__cxa_throw:(a,b,c)=>{var d=new Fa(a);G[d.h+16>>2]=0;G[d.h+4>>2]=
b;G[d.h+8>>2]=c;Eb(a);L=a;Ea++;throw L;},__cxa_uncaught_exceptions:()=>Ea,__resumeException:a=>{L||=a;throw L;},_abort_js:()=>ta(""),_embind_register_bigint:(a,b,c,d,e)=>{b=N(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=k=>BigInt.asUintN(g,k);e=f(e)}R(a,{name:b,g:f,l:(g,k)=>{"number"==typeof k&&(k=BigInt(k));return k},m:La(b,c,!d),j:null})},_embind_register_bool:(a,b,c,d)=>{b=N(b);R(a,{name:b,g:function(e){return!!e},l:function(e,f){return f?c:d},m:function(e){return this.g(C[e])},j:null})},_embind_register_emval:a=>
R(a,Pa),_embind_register_float:(a,b,c)=>{b=N(b);R(a,{name:b,g:d=>d,l:(d,e)=>e,m:Qa(b,c),j:null})},_embind_register_function:(a,b,c,d,e,f,g)=>{var k=Va(b,c);a=N(a);a=gb(a);e=Za(d,e);Ua(a,function(){cb(`Cannot call ${a} due to unbound types`,k)},b-1);fb(k,m=>{var l=[m[0],null].concat(m.slice(1));m=a;var p=a;var y=e,n=l.length;if(2>n)throw new Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var z=null!==l[1]&&!1,J=Sa(l),da=!l[0].v,w=l[0],x=l[1];y=[p,Ja,y,f,Ra,w.g.bind(w),
x?.l.bind(x)];for(w=2;w<n;++w)x=l[w],y.push(x.l.bind(x));if(!J)for(w=z?1:2;w<l.length;++w)null!==l[w].j&&y.push(l[w].j);J=Sa(l);w=l.length-2;var A=[];x=["fn"];z&&x.push("thisWired");for(n=0;n<w;++n)A.push(`arg${n}`),x.push(`arg${n}Wired`);A=A.join(",");x=x.join(",");A=`return function (${A}) {\n`;J&&(A+="var destructors = [];\n");var db=J?"destructors":"null",xa="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");z&&(A+=`var thisWired = toClassParamWire(${db}, this);\n`);
for(n=0;n<w;++n){var eb=`toArg${n}Wire`;A+=`var arg${n}Wired = ${eb}(${db}, arg${n});\n`;xa.push(eb)}A+=(da||g?"var rv = ":"")+`invoker(${x});\n`;if(J)A+="runDestructors(destructors);\n";else for(n=z?1:2;n<l.length;++n)z=1===n?"thisWired":"arg"+(n-2)+"Wired",null!==l[n].j&&(A+=`${z}_dtor(${z});\n`,xa.push(`${z}_dtor`));da&&(A+="var ret = fromRetWire(rv);\nreturn ret;\n");l=(new Function(xa,A+"}\n"))(...y);p=Object.defineProperty(l,"name",{value:p});l=b-1;if(!h.hasOwnProperty(m))throw new Wa("Replacing nonexistent public symbol");
void 0!==h[m].i&&void 0!==l?h[m].i[l]=p:(h[m]=p,h[m].o=l);return[]})},_embind_register_integer:(a,b,c,d,e)=>{b=N(b);let f=k=>k;if(0===d){var g=32-8*c;f=k=>k<<g>>>g;e=f(e)}R(a,{name:b,g:f,l:(k,m)=>m,m:La(b,c,0!==d),j:null})},_embind_register_memory_view:(a,b,c)=>{function d(f){return new e(B.buffer,G[f+4>>2],G[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=N(c);R(a,{name:c,g:d,m:d},{u:!0})},_embind_register_std_string:(a,
b)=>{b=N(b);R(a,{name:b,g(c){var d=lb(c+4,G[c>>2],!0);U(c);return d},l(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new Q("Cannot pass non-string to std::string");var f=e?hb(d):d.length;var g=Bb(4+f+1),k=g+4;G[g>>2]=f;e?V(d,k,f+1):C.set(d,k);null!==c&&c.push(U,g);return g},m:Oa,j(c){U(c)}})},_embind_register_std_wstring:(a,b,c)=>{c=N(c);if(2===b){var d=nb;var e=ob;var f=pb}else d=qb,e=rb,f=sb;R(a,{name:c,
g:g=>{var k=d(g+4,G[g>>2]*b,!0);U(g);return k},l:(g,k)=>{if("string"!=typeof k)throw new Q(`Cannot pass non-string to C++ string type ${c}`);var m=f(k),l=Bb(4+m+b);G[l>>2]=m/b;e(k,l+4,m+b);null!==g&&g.push(U,l);return l},m:Oa,j(g){U(g)}})},_embind_register_void:(a,b)=>{b=N(b);R(a,{v:!0,name:b,g:()=>{},l:()=>{}})},_emscripten_runtime_keepalive_clear:()=>{I=!1;tb=0},_setitimer_js:(a,b)=>{W[a]&&(clearTimeout(W[a].id),delete W[a]);if(!b)return 0;var c=setTimeout(()=>{delete W[a];vb(()=>Cb(a,performance.now()))},
b);W[a]={id:c,A:b};return 0},_tzset_js:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();G[a>>2]=60*Math.max(f,e);F[b>>2]=Number(f!=e);b=g=>{var k=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(V(a,c,17),V(b,d,17)):(V(a,d,17),V(b,c,17))},emscripten_resize_heap:a=>{var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*
(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-H.buffer.byteLength+65535)/65536|0;try{H.grow(d);sa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},environ_get:(a,b)=>{var c=0,d=0,e;for(e of yb()){var f=b+c;G[a+d>>2]=f;c+=V(e,f,Infinity)+1;d+=4}return 0},environ_sizes_get:(a,b)=>{var c=yb();G[a>>2]=c.length;a=0;for(var d of c)a+=hb(d)+1;G[b>>2]=a;return 0},invoke_ii:Gb,invoke_iii:Hb,invoke_iiii:Ib,invoke_iiiii:Jb,invoke_iiiiid:Kb,invoke_iiiiiii:Lb,
invoke_iiiiiiii:Mb,invoke_iiiiiiiiiiii:Nb,invoke_iij:Ob,invoke_v:Pb,invoke_vi:Qb,invoke_vii:Rb,invoke_viii:Sb,invoke_viiiii:Tb,invoke_viiiiiii:Ub,invoke_viiiiiiii:Vb,invoke_viiiiiiiiii:Wb,invoke_viiiiiiiiiiiiiii:Xb,proc_exit:ub};function Gb(a,b){var c=X();try{return T(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}function Rb(a,b,c){var d=X();try{T(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function Pb(a){var b=X();try{T(a)()}catch(c){Y(b);if(c!==c+0)throw c;Z(1,0)}}
function Hb(a,b,c){var d=X();try{return T(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function Qb(a,b){var c=X();try{T(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}function Kb(a,b,c,d,e,f){var g=X();try{return T(a)(b,c,d,e,f)}catch(k){Y(g);if(k!==k+0)throw k;Z(1,0)}}function Sb(a,b,c,d){var e=X();try{T(a)(b,c,d)}catch(f){Y(e);if(f!==f+0)throw f;Z(1,0)}}function Ib(a,b,c,d){var e=X();try{return T(a)(b,c,d)}catch(f){Y(e);if(f!==f+0)throw f;Z(1,0)}}
function Ob(a,b,c){var d=X();try{return T(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function Mb(a,b,c,d,e,f,g,k){var m=X();try{return T(a)(b,c,d,e,f,g,k)}catch(l){Y(m);if(l!==l+0)throw l;Z(1,0)}}function Jb(a,b,c,d,e){var f=X();try{return T(a)(b,c,d,e)}catch(g){Y(f);if(g!==g+0)throw g;Z(1,0)}}function Ub(a,b,c,d,e,f,g,k){var m=X();try{T(a)(b,c,d,e,f,g,k)}catch(l){Y(m);if(l!==l+0)throw l;Z(1,0)}}
function Lb(a,b,c,d,e,f,g){var k=X();try{return T(a)(b,c,d,e,f,g)}catch(m){Y(k);if(m!==m+0)throw m;Z(1,0)}}function Nb(a,b,c,d,e,f,g,k,m,l,p,y){var n=X();try{return T(a)(b,c,d,e,f,g,k,m,l,p,y)}catch(z){Y(n);if(z!==z+0)throw z;Z(1,0)}}function Tb(a,b,c,d,e,f){var g=X();try{T(a)(b,c,d,e,f)}catch(k){Y(g);if(k!==k+0)throw k;Z(1,0)}}function Vb(a,b,c,d,e,f,g,k,m){var l=X();try{T(a)(b,c,d,e,f,g,k,m)}catch(p){Y(l);if(p!==p+0)throw p;Z(1,0)}}
function Wb(a,b,c,d,e,f,g,k,m,l,p){var y=X();try{T(a)(b,c,d,e,f,g,k,m,l,p)}catch(n){Y(y);if(n!==n+0)throw n;Z(1,0)}}function Xb(a,b,c,d,e,f,g,k,m,l,p,y,n,z,J,da){var w=X();try{T(a)(b,c,d,e,f,g,k,m,l,p,y,n,z,J,da)}catch(x){Y(w);if(x!==x+0)throw x;Z(1,0)}}var Zb;
Zb=await (async function(){function a(c){c=Zb=c.exports;ab=c.__getTypeName;h._parse=c.parse;h._convert=c.convert;Bb=h._malloc=c.malloc;Cb=c._emscripten_timeout;U=h._free=c.free;Z=c.setThrew;M=c._emscripten_tempret_set;Y=c._emscripten_stack_restore;zb=c._emscripten_stack_alloc;X=c.emscripten_stack_get_current;Db=c.__cxa_decrement_exception_refcount;Eb=c.__cxa_increment_exception_refcount;Ga=c.__cxa_can_catch;Fb=c.__cxa_get_exception_ptr;H=c.memory;Ya=c.__indirect_function_table;sa();return Zb}
var b={env:Yb,wasi_snapshot_preview1:Yb};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ua??=h.locateFile?h.locateFile?h.locateFile("hpop_wasm.wasm",r):r+"hpop_wasm.wasm":(new URL("hpop_wasm.wasm",import.meta.url)).href;return a((await ya(b)).instance)}());
(function(){function a(){h.calledRun=!0;if(!v){ra=!0;Zb.__wasm_call_ctors();la?.(h);h.onRuntimeInitialized?.();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();Ba.push(b)}Aa(Ba)}}if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Da();Aa(Ca);h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);a()},1)):a()})();ra?moduleRtn=h:moduleRtn=new Promise((a,b)=>{la=a;ma=b});
;return moduleRtn}export default HPOP_WASM;
