async function HPOP_WASM(moduleArg={}){var moduleRtn;var k=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(ca){const {createRequire:a}=await import("node:module");var require=a(import.meta.url)}var da="./this.program",q=(a,b)=>{throw b;},ea=import.meta.url,r="",ha,ia;
if(ca){var fs=require("node:fs");ea.startsWith("file:")&&(r=require("node:path").dirname(require("node:url").fileURLToPath(ea))+"/");ia=a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a)};ha=async a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);q=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{r=(new URL(".",ea)).href}catch{}ha=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();
throw Error(a.status+" : "+a.url);}}console.log.bind(console);var t=console.error.bind(console),u,v=!1,ka,ja=a=>a.startsWith("file://"),la,ma,B,C,D,E,F,G,na,oa,pa,qa,ra=!1;function sa(){var a=H.buffer;B=new Int8Array(a);D=new Int16Array(a);C=new Uint8Array(a);E=new Uint16Array(a);F=new Int32Array(a);G=new Uint32Array(a);na=new Float32Array(a);oa=new Float64Array(a);pa=new BigInt64Array(a);qa=new BigUint64Array(a)}
function ta(a){k.onAbort?.(a);a="Aborted("+a+")";t(a);v=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ma?.(a);throw a;}var ua;async function va(a){if(!u)try{var b=await ha(a);return new Uint8Array(b)}catch{}if(a==ua&&u)a=new Uint8Array(u);else if(ia)a=ia(a);else throw"both async and sync fetching of the wasm failed";return a}
async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){t(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}async function xa(a){var b=ua;if(!u&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){t(`wasm streaming compile failed: ${d}`),t("falling back to ArrayBuffer instantiation")}return wa(b,a)}
class ya{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var za=a=>{for(;0<a.length;)a.shift()(k)},Aa=[],Ba=[],Da=()=>{var a=k.preRun.shift();Ba.push(a)},Ea=!0,Fa=[],Ga=0,I=0;class Ha{constructor(a){this.s=a;this.h=a-24}}
var Ja=a=>{var b=I;if(!b)return J(0),0;var c=new Ha(b);G[c.h+16>>2]=b;var d=G[c.h+4>>2];if(!d)return J(0),b;for(var e of a){if(0===e||e===d)break;if(Ia(e,d,c.h+16))return J(e),b}J(d);return b},K=a=>{for(var b="";;){var c=C[a++];if(!c)return b;b+=String.fromCharCode(c)}},M={},N={},Ka={},O=class extends Error{constructor(a){super(a);this.name="BindingError"}},La=a=>{throw new O(a);};
function Ma(a,b,c={}){var d=b.name;if(!a)throw new O(`type "${d}" must have a positive integer typeid pointer`);if(N.hasOwnProperty(a)){if(c.v)return;throw new O(`Cannot register type '${d}' twice`);}N[a]=b;delete Ka[a];M.hasOwnProperty(a)&&(b=M[a],delete M[a],b.forEach(e=>e()))}function P(a,b,c={}){return Ma(a,b,c)}
var Na=(a,b,c)=>{switch(b){case 1:return c?d=>B[d]:d=>C[d];case 2:return c?d=>D[d>>1]:d=>E[d>>1];case 4:return c?d=>F[d>>2]:d=>G[d>>2];case 8:return c?d=>pa[d>>3]:d=>qa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Oa=[],Q=[0,1,,1,null,1,!0,1,!1,1],Pa=a=>{9<a&&0===--Q[a+1]&&(Q[a]=void 0,Oa.push(a))},R=a=>{if(!a)throw new O(`Cannot use deleted val. handle = ${a}`);return Q[a]},S=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=
Oa.pop()||Q.length;Q[b]=a;Q[b+1]=1;return b}};function Qa(a){return this.g(G[a>>2])}var Ra={name:"emscripten::val",g:a=>{var b=R(a);Pa(a);return b},l:(a,b)=>S(b),m:Qa,j:null},Sa=(a,b)=>{switch(b){case 4:return function(c){return this.g(na[c>>2])};case 8:return function(c){return this.g(oa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ta=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Ua(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].j)return!0;return!1}
var Va=(a,b)=>{if(void 0===k[a].i){var c=k[a];k[a]=function(...d){if(!k[a].i.hasOwnProperty(d.length))throw new O(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${k[a].i})!`);return k[a].i[d.length].apply(this,d)};k[a].i=[];k[a].i[c.o]=c}},Wa=(a,b,c)=>{if(k.hasOwnProperty(a)){if(void 0===c||void 0!==k[a].i&&void 0!==k[a].i[c])throw new O(`Cannot register public name '${a}' twice`);Va(a,a);if(k[a].i.hasOwnProperty(c))throw new O(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
k[a].i[c]=b}else k[a]=b,k[a].o=c},Xa=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(G[b+4*d>>2]);return c},Ya=class extends Error{constructor(a){super(a);this.name="InternalError"}},Za=[],T=a=>{var b=Za[a];b||(Za[a]=b=$a.get(a));return b},ab=(a,b)=>{a=K(a);var c=T(b);if("function"!=typeof c)throw new O(`unknown function pointer with signature ${a}: ${b}`);return c};class bb extends Error{}
var db=a=>{a=cb(a);var b=K(a);U(a);return b},eb=(a,b)=>{function c(f){e[f]||N[f]||(Ka[f]?Ka[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new bb(`${a}: `+d.map(db).join([", "]));},fb=(a,b)=>{function c(h){h=b(h);if(h.length!==d.length)throw new Ya("Mismatched type converter count");for(var m=0;m<d.length;++m)P(d[m],h[m])}var d=[];d.forEach(h=>Ka[h]=a);var e=Array(a.length),f=[],g=0;for(let [h,m]of a.entries())N.hasOwnProperty(m)?e[h]=N[m]:(f.push(m),M.hasOwnProperty(m)||(M[m]=
[]),M[m].push(()=>{e[h]=N[m];++g;g===f.length&&c(e)}));0===f.length&&c(e)},gb=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},V=(a,b,c)=>{var d=C;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(b>=c)break;d[b++]=g}else if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6;d[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12;d[b++]=128|g>>6&63;d[b++]=128|g&63}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63;d[b++]=
128|g>>6&63;d[b++]=128|g&63;f++}}d[b]=0;return b-e},hb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ib=globalThis.TextDecoder&&new TextDecoder,jb=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},mb=(a=0,b,c)=>{var d=C;b=jb(d,a,b,c);if(16<b-a&&d.buffer&&ib)return ib.decode(d.subarray(a,b));for(c="";a<b;){var e=d[a++];if(e&128){var f=d[a++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=
d[a++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|d[a++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},nb=(a,b,c)=>a?mb(a,b,c):"",ob=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,pb=(a,b,c)=>{a>>=1;b=jb(E,a,b/2,c);if(16<b-a&&ob)return ob.decode(E.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(E[a]);return c},qb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?
c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d},rb=a=>2*a.length,sb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=G[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},tb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;F[b>>2]=f;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d},ub=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},vb=0,wb=[],xb=a=>{var b=
wb.length;wb.push(a);return b},yb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=G[b+4*d>>2],g=N[f];if(void 0===g)throw a=`${`parameter ${d}`} has unknown type ${db(f)}`,new O(a);c[e]=g}return c},zb=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(G[b>>2]=S(d));return a},Ab={},Bb=a=>{var b=Ab[a];return void 0===b?K(a):b},W={},Cb=a=>{ka=a;Ea||0<vb||(k.onExit?.(a),v=!0);q(a,new ya(a))},Db=a=>{if(!v)try{a()}catch(b){b instanceof ya||"unwind"==b||q(1,b)}finally{if(!(Ea||0<vb))try{ka=a=ka,Cb(a)}catch(b){b instanceof
ya||"unwind"==b||q(1,b)}}},Eb={},Gb=()=>{if(!Fb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Eb)void 0===Eb[b]?delete a[b]:a[b]=Eb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Fb=c}return Fb},Fb,Ib=(a,b,c,d)=>{var e={string:l=>{var n=0;if(null!==l&&void 0!==l&&0!==l){n=hb(l)+1;var y=Hb(n);V(l,y,n);n=y}return n},array:l=>{var n=Hb(l.length);B.set(l,n);return n}};
a=k["_"+a];var f=[],g=0;if(d)for(var h=0;h<d.length;h++){var m=e[c[h]];m?(0===g&&(g=X()),f[h]=m(d[h])):f[h]=d[h]}c=a(...f);return c=function(l){0!==g&&Y(g);return"string"===b?l?mb(l):"":"boolean"===b?!!l:l}(c)};k.noExitRuntime&&(Ea=k.noExitRuntime);k.printErr&&(t=k.printErr);k.wasmBinary&&(u=k.wasmBinary);k.thisProgram&&(da=k.thisProgram);if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.shift()();k.ccall=Ib;
k.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?k["_"+a]:(...f)=>Ib(a,b,c,f,d)};k.UTF8ToString=nb;k.stringToUTF8=(a,b,c)=>V(a,b,c);k.lengthBytesUTF8=hb;
var cb,Jb,U,Kb,Z,J,Y,Hb,X,Lb,Mb,Ia,Nb,H,$a,fc={__cxa_begin_catch:a=>{var b=new Ha(a);0==B[b.h+12]&&(B[b.h+12]=1,Ga--);B[b.h+13]=0;Fa.push(b);return Nb(a)},__cxa_end_catch:()=>{Z(0,0);var a=Fa.pop();Lb(a.s);I=0},__cxa_find_matching_catch_2:()=>Ja([]),__cxa_find_matching_catch_3:a=>Ja([a]),__cxa_rethrow:()=>{var a=Fa.pop();a||ta("no exception to throw");var b=a.s;0==B[a.h+13]&&(Fa.push(a),B[a.h+13]=1,B[a.h+12]=0,Ga++);Mb(b);I=b;throw I;},__cxa_throw:(a,b,c)=>{var d=new Ha(a);G[d.h+16>>2]=0;G[d.h+4>>
2]=b;G[d.h+8>>2]=c;Mb(a);I=a;Ga++;throw I;},__cxa_uncaught_exceptions:()=>Ga,__resumeException:a=>{I||=a;throw I;},_abort_js:()=>ta(""),_embind_register_bigint:(a,b,c,d,e)=>{b=K(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}P(a,{name:b,g:f,l:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},m:Na(b,c,!d),j:null})},_embind_register_bool:(a,b,c,d)=>{b=K(b);P(a,{name:b,g:function(e){return!!e},l:function(e,f){return f?c:d},m:function(e){return this.g(C[e])},j:null})},_embind_register_emval:a=>
P(a,Ra),_embind_register_float:(a,b,c)=>{b=K(b);P(a,{name:b,g:d=>d,l:(d,e)=>e,m:Sa(b,c),j:null})},_embind_register_function:(a,b,c,d,e,f,g)=>{var h=Xa(b,c);a=K(a);a=gb(a);e=ab(d,e);Wa(a,function(){eb(`Cannot call ${a} due to unbound types`,h)},b-1);fb(h,m=>{var l=[m[0],null].concat(m.slice(1));m=a;var n=a;var y=e,p=l.length;if(2>p)throw new O("argTypes array size mismatch! Must at least get return value and 'this' types!");var z=null!==l[1]&&!1,L=Ua(l),fa=!l[0].u,w=l[0],x=l[1];y=[n,La,y,f,Ta,w.g.bind(w),
x?.l.bind(x)];for(w=2;w<p;++w)x=l[w],y.push(x.l.bind(x));if(!L)for(w=z?1:2;w<l.length;++w)null!==l[w].j&&y.push(l[w].j);L=Ua(l);w=l.length-2;var A=[];x=["fn"];z&&x.push("thisWired");for(p=0;p<w;++p)A.push(`arg${p}`),x.push(`arg${p}Wired`);A=A.join(",");x=x.join(",");A=`return function (${A}) {\n`;L&&(A+="var destructors = [];\n");var kb=L?"destructors":"null",Ca="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");z&&(A+=`var thisWired = toClassParamWire(${kb}, this);\n`);
for(p=0;p<w;++p){var lb=`toArg${p}Wire`;A+=`var arg${p}Wired = ${lb}(${kb}, arg${p});\n`;Ca.push(lb)}A+=(fa||g?"var rv = ":"")+`invoker(${x});\n`;if(L)A+="runDestructors(destructors);\n";else for(p=z?1:2;p<l.length;++p)z=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==l[p].j&&(A+=`${z}_dtor(${z});\n`,Ca.push(`${z}_dtor`));fa&&(A+="var ret = fromRetWire(rv);\nreturn ret;\n");l=(new Function(Ca,A+"}\n"))(...y);n=Object.defineProperty(l,"name",{value:n});l=b-1;if(!k.hasOwnProperty(m))throw new Ya("Replacing nonexistent public symbol");
void 0!==k[m].i&&void 0!==l?k[m].i[l]=n:(k[m]=n,k[m].o=l);return[]})},_embind_register_integer:(a,b,c,d,e)=>{b=K(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}P(a,{name:b,g:f,l:(h,m)=>m,m:Na(b,c,0!==d),j:null})},_embind_register_memory_view:(a,b,c)=>{function d(f){return new e(B.buffer,G[f+4>>2],G[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=K(c);P(a,{name:c,g:d,m:d},{v:!0})},_embind_register_std_string:(a,
b)=>{b=K(b);P(a,{name:b,g(c){var d=nb(c+4,G[c>>2],!0);U(c);return d},l(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new O("Cannot pass non-string to std::string");var f=e?hb(d):d.length;var g=Jb(4+f+1),h=g+4;G[g>>2]=f;e?V(d,h,f+1):C.set(d,h);null!==c&&c.push(U,g);return g},m:Qa,j(c){U(c)}})},_embind_register_std_wstring:(a,b,c)=>{c=K(c);if(2===b){var d=pb;var e=qb;var f=rb}else d=sb,e=tb,f=ub;P(a,{name:c,
g:g=>{var h=d(g+4,G[g>>2]*b,!0);U(g);return h},l:(g,h)=>{if("string"!=typeof h)throw new O(`Cannot pass non-string to C++ string type ${c}`);var m=f(h),l=Jb(4+m+b);G[l>>2]=m/b;e(h,l+4,m+b);null!==g&&g.push(U,l);return l},m:Qa,j(g){U(g)}})},_embind_register_void:(a,b)=>{b=K(b);P(a,{u:!0,name:b,g:()=>{},l:()=>{}})},_emscripten_runtime_keepalive_clear:()=>{Ea=!1;vb=0},_emval_create_invoker:(a,b,c)=>{var [d,...e]=yb(a,b);b=d.l.bind(d);var f=e.map(m=>m.m.bind(m));a--;var g={toValue:R};a=f.map((m,l)=>{var n=
`argFromPtr${l}`;g[n]=m;return`${n}(args${l?"+"+8*l:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:g.getStringOrSymbol=Bb,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;d.u||(g.toReturnWire=b,g.emval_returnValue=zb,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n${h}\n}`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=
`methodCaller<(${e.map(m=>m.name)}) => ${d.name}>`;return xb(Object.defineProperty(c,"name",{value:h}))},_emval_decref:Pa,_emval_get_global:a=>{if(!a)return S(globalThis);a=Bb(a);return S(globalThis[a])},_emval_get_property:(a,b)=>{a=R(a);b=R(b);return S(a[b])},_emval_incref:a=>{9<a&&(Q[a+1]+=1)},_emval_invoke:(a,b,c,d,e)=>wb[a](b,c,d,e),_emval_new_cstring:a=>S(Bb(a)),_emval_run_destructors:a=>{var b=R(a);Ta(b);Pa(a)},_setitimer_js:(a,b)=>{W[a]&&(clearTimeout(W[a].id),delete W[a]);if(!b)return 0;
var c=setTimeout(()=>{delete W[a];Db(()=>Kb(a,performance.now()))},b);W[a]={id:c,A:b};return 0},_tzset_js:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();G[a>>2]=60*Math.max(f,e);F[b>>2]=Number(f!=e);b=g=>{var h=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(h/60)).padStart(2,"0")}${String(h%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(V(a,c,17),V(b,d,17)):(V(a,d,17),V(b,c,17))},emscripten_resize_heap:a=>{var b=C.length;
a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-H.buffer.byteLength+65535)/65536|0;try{H.grow(d);sa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},environ_get:(a,b)=>{var c=0,d=0,e;for(e of Gb()){var f=b+c;G[a+d>>2]=f;c+=V(e,f,Infinity)+1;d+=4}return 0},environ_sizes_get:(a,b)=>{var c=Gb();G[a>>2]=c.length;a=0;for(var d of c)a+=hb(d)+1;G[b>>2]=a;return 0},invoke_ii:Ob,invoke_iii:Pb,
invoke_iiii:Qb,invoke_iiiii:Rb,invoke_iiiiid:Sb,invoke_iiiiiii:Tb,invoke_iiiiiiii:Ub,invoke_iiiiiiiiiiii:Vb,invoke_iij:Wb,invoke_v:Xb,invoke_vi:Yb,invoke_vii:Zb,invoke_viii:$b,invoke_viiiii:ac,invoke_viiiiiii:bc,invoke_viiiiiiii:cc,invoke_viiiiiiiiii:dc,invoke_viiiiiiiiiiiiiii:ec,proc_exit:Cb};function Pb(a,b,c){var d=X();try{return T(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function Ob(a,b){var c=X();try{return T(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}
function Zb(a,b,c){var d=X();try{T(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function Yb(a,b){var c=X();try{T(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;Z(1,0)}}function Xb(a){var b=X();try{T(a)()}catch(c){Y(b);if(c!==c+0)throw c;Z(1,0)}}function Tb(a,b,c,d,e,f,g){var h=X();try{return T(a)(b,c,d,e,f,g)}catch(m){Y(h);if(m!==m+0)throw m;Z(1,0)}}function Sb(a,b,c,d,e,f){var g=X();try{return T(a)(b,c,d,e,f)}catch(h){Y(g);if(h!==h+0)throw h;Z(1,0)}}
function $b(a,b,c,d){var e=X();try{T(a)(b,c,d)}catch(f){Y(e);if(f!==f+0)throw f;Z(1,0)}}function Qb(a,b,c,d){var e=X();try{return T(a)(b,c,d)}catch(f){Y(e);if(f!==f+0)throw f;Z(1,0)}}function Wb(a,b,c){var d=X();try{return T(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;Z(1,0)}}function Ub(a,b,c,d,e,f,g,h){var m=X();try{return T(a)(b,c,d,e,f,g,h)}catch(l){Y(m);if(l!==l+0)throw l;Z(1,0)}}function Rb(a,b,c,d,e){var f=X();try{return T(a)(b,c,d,e)}catch(g){Y(f);if(g!==g+0)throw g;Z(1,0)}}
function bc(a,b,c,d,e,f,g,h){var m=X();try{T(a)(b,c,d,e,f,g,h)}catch(l){Y(m);if(l!==l+0)throw l;Z(1,0)}}function Vb(a,b,c,d,e,f,g,h,m,l,n,y){var p=X();try{return T(a)(b,c,d,e,f,g,h,m,l,n,y)}catch(z){Y(p);if(z!==z+0)throw z;Z(1,0)}}function ac(a,b,c,d,e,f){var g=X();try{T(a)(b,c,d,e,f)}catch(h){Y(g);if(h!==h+0)throw h;Z(1,0)}}function cc(a,b,c,d,e,f,g,h,m){var l=X();try{T(a)(b,c,d,e,f,g,h,m)}catch(n){Y(l);if(n!==n+0)throw n;Z(1,0)}}
function dc(a,b,c,d,e,f,g,h,m,l,n){var y=X();try{T(a)(b,c,d,e,f,g,h,m,l,n)}catch(p){Y(y);if(p!==p+0)throw p;Z(1,0)}}function ec(a,b,c,d,e,f,g,h,m,l,n,y,p,z,L,fa){var w=X();try{T(a)(b,c,d,e,f,g,h,m,l,n,y,p,z,L,fa)}catch(x){Y(w);if(x!==x+0)throw x;Z(1,0)}}var gc;
gc=await (async function(){function a(c){c=gc=c.exports;cb=c.__getTypeName;k._parse=c.parse;k._convert=c.convert;Jb=k._malloc=c.malloc;U=k._free=c.free;Kb=c._emscripten_timeout;Z=c.setThrew;J=c._emscripten_tempret_set;Y=c._emscripten_stack_restore;Hb=c._emscripten_stack_alloc;X=c.emscripten_stack_get_current;Lb=c.__cxa_decrement_exception_refcount;Mb=c.__cxa_increment_exception_refcount;Ia=c.__cxa_can_catch;Nb=c.__cxa_get_exception_ptr;H=c.memory;$a=c.__indirect_function_table;sa();return gc}
var b={env:fc,wasi_snapshot_preview1:fc};if(k.instantiateWasm)return new Promise(c=>{k.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ua??=k.locateFile?k.locateFile?k.locateFile("hpop_wasm.wasm",r):r+"hpop_wasm.wasm":(new URL("hpop_wasm.wasm",import.meta.url)).href;return a((await xa(b)).instance)}());
(function(){function a(){k.calledRun=!0;if(!v){ra=!0;gc.__wasm_call_ctors();la?.(k);k.onRuntimeInitialized?.();if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;){var b=k.postRun.shift();Aa.push(b)}za(Aa)}}if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Da();za(Ba);k.setStatus?(k.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>k.setStatus(""),1);a()},1)):a()})();ra?moduleRtn=k:moduleRtn=new Promise((a,b)=>{la=a;ma=b});
;return moduleRtn}export default HPOP_WASM;
